### ISSUE TITLE
有没有baikal-client api如何使用的example呢

### ISSUE THREAD

**Issue by lkkey80** [baidu/BaikalDB#101]
能提供一下baikal-client api如何使用的例子吗

**Comment by lgqss** [comment]
我整理下文档，下周发布到wiki系统

**Comment by lkkey80** [comment]
另外，使用bazel build //:all 编译的时候baikal-client没有进行编译

**Comment by lgqss** [comment]
https://github.com/baidu/BaikalDB/wiki/baikal-cleint-usage
client比较独立，bazel 编译还未适配，可以使用cmake
