### ISSUE TITLE
有评估过baikaldb使用的protobuf动态消息的性能吗

### ISSUE THREAD

**Issue by lkkey80** [baidu/BaikalDB#104]
有评估过baikaldb使用的protobuf动态消息的性能吗？根据SchemaInfo动态生成和解析message相比直接定义或者动态编译proto性能相差大吗？

**Comment by lgqss** [comment]
parse和serialize基本没区别，反射获取数据，还是会有些消耗，不过rocksdb的get消耗相比还是小的多的
另外parse我们自己实现了一个，可以只解析部分列https://github.com/baidu/BaikalDB/blob/master/src/common/tuple_record.cpp
