### ISSUE TITLE
能详细介绍一下BaikalDB基于raft和rocksdb的快照机制的实现原理吗

### ISSUE THREAD

**Issue by lkkey80** [baidu/BaikalDB#105]
能详细介绍一下BaikalDB基于raft和rocksdb的快照机制的实现原理吗

**Comment by lgqss** [comment]
你是指哪个snapshot，raft的install snapshot流程？

**Comment by lkkey80** [comment]
是的，region snapshot load 流程和机制

**Comment by lgqss** [comment]
src/raft/rocksdb_file_system_adaptor.cpp
主要是这个文件实现，先建立rocksdb的snapshot，然后read过程把数据读出后发送给follower
follower实现write过程，把数据写成sst
on_snapshot_load把sst ingest到rocksdb里

**Comment by lkkey80** [comment]
在braft 回调Region::on_snapshot_save 里没有创建rocksdb snapshot，而是在RocksdbFileSystemAdaptor的open_snapshot里创建快照。这样保存在SnapshotMeta里的last_included_term和last_included_index不就和真正创建快照时不匹配了吗？

**Comment by lkkey80** [comment]
知道了，利用rocksdb key-value操作的幂等性，后面log追赶的时候，多执行一遍key-value操作，最终结果也是一致的。

**Comment by lgqss** [comment]
RocksdbFileSystemAdaptor里面也记录了applied_index，最终回放日志，<applied_index 会忽略
https://github.com/baidu/BaikalDB/blob/master/src/store/region.cpp#L2177

**Comment by lkkey80** [comment]
因为rocksdb key-value操作的幂等特性，如果on_apply回放日志时不根据 iter.index() <= _applied_index 过滤掉已经apply 过的log，重新执行一遍也没有问题的吧？不考虑效率因素

**Comment by luobuda** [comment]
> ue操作的幂等特性，如果on_apply回放日志时不根据 iter.index() <= _applied_index 过滤掉已经apply 过的log，重新执行一遍也没有问题的吧？

如果是update这种操作，不能重复执行的，所以需要过滤掉

**Comment by lkkey80** [comment]
是有其他考虑因素吗，单纯的考虑rocksdb的重复update应当不会有问题吧

**Comment by luobuda** [comment]
> 是有其他考虑因素吗，单纯的考虑rocksdb的重复update应当不会有问题吧

假设你的字段a=1，请求是 set a=a+1，重复执行的话a=3了，数据不对了
