### ISSUE TITLE
CMake build issue

### ISSUE THREAD

**Issue by Cr1t-GYM** [baidu/BaikalDB#107]
I have installed bison and flex, but CMake still reported the error following:
CMake Error at CMakeLists.txt:278 (message):
  failed to generate expression, please install flex and bison first

-- Configuring incomplete, errors occurred!

**Comment by Cr1t-GYM** [comment]
Done. Have to change the command in gen_source.sh based on personal settings.

**Comment by luobuda** [comment]
> Done. Have to change the command in gen_source.sh based on personal settings.

yes，you should set right PATH of flex and bison  in gen_source.sh:
`cd include/sqlparser && /opt/compiler/gcc-4.8.2/bin/flex sql_lex.l && /opt/compiler/gcc-4.8.2/bin/bison sql_parse.y`

**Comment by lgqss** [comment]
I've fixed in https://github.com/baidu/BaikalDB/pull/108
