### ISSUE TITLE
BaikalDB是如何解决写和更新请求的重复执行问题的？

### ISSUE THREAD

**Issue by lkkey80** [baidu/BaikalDB#110]
BaikalDB是如何解决写和更新请求的重复执行问题的？比如client 发一个update table 中某一列的请求，但是BaiKalStore的应答超时了，然后client发起重试，会不会导致问题？

**Comment by lgqss** [comment]
同一个事务里有个seq_id，重试seq_id会保持不变

**Comment by luobuda** [comment]
非事务场景还存在这个问题

**Comment by lkkey80** [comment]
如果是类似update x = x +1 这种请求重复执行会导致问题，有修复的计划吗

**Comment by luobuda** [comment]
对于这种请求可以考虑超时不重试
