### ISSUE TITLE
BaikalDB是如何保证线性一致性读的

### ISSUE THREAD

**Issue by lkkey80** [baidu/BaikalDB#115]
在 Region::exec_out_txn_query 看到如果是pb::OP_SELECT请求并没有走raft状态机，而且也没有看到其他的类似raft read index处理方法。请问BaikalDB是如何保证线性一致性查询的？

**Comment by luobuda** [comment]
目前还没有支持follower一致性读，一直读需要开事务，类似raft read index处理方法之后会引入的。

**Comment by lgqss** [comment]
默认是读leader，我们的leader是控制on_leader_start后才算leader成功，所以不走状态机也能保证一致性，前提是要开事务读，非事务读现在不判断leader状态

**Comment by lkkey80** [comment]
简单看了下Region::on_apply(braft::Iterator& iter)的实现，看上去全部是串行apply，当然这样可以保证"默认是读leader，我们的leader是控制on_leader_start后才算leader成功，所以不走状态机也能保证一致性"，有没有考虑将on_apply里的apply任务做成并行的，这样应当能提升不少性能，当然这样会增加线性一致性读的处理难度。

**Comment by lgqss** [comment]
并行的话也考虑过，这块影响的不只是读了，写过程中core了如何回溯是个问题。然后单节点有n个raft，写比较均匀的话本身就是并发写的了。
