### ISSUE TITLE
是否支持mac上编译？

### ISSUE THREAD

**Issue by yvxiang** [baidu/BaikalDB#12]
如题

**Comment by yvxiang** [comment]
另外，是否有微信交流群？

**Comment by lgqss** [comment]
不支持在mac上编译，如果需要测试学习，可以通过mac上安装ubuntu虚拟机，而且默认配置占用内存比较多，可能需要调整一些参数才能在虚拟机运行起来
目前还没有微信群，微信群拉人不大方便，我们内部讨论下，可能用qq群更方便些，近期会发布一个release版本，到时候会建设交流群
目前如果技术交流可以先加我微信lqgss

**Comment by lgqss** [comment]
> lqgss
不好意思，微信号写错了，是lgq0925 ..

**Comment by tullyliu** [comment]
baikaldb主要在linux 运行，mac编译支持意义不大，短期不会考虑支持
