### ISSUE TITLE
Table partition compatibility: cannot partition by hash

### ISSUE THREAD

**Issue by zhangysh1995** [baidu/BaikalDB#121]
**Describe the bug**
Cannot create a table partitioned by hash

**To Reproduce**
Run the following query to create a table:

````
create table table_5_utf8_2 (
`pk` int primary key
) character set utf8
partition by hash(pk)
partitions 2;
````

**Expected behavior**
The table should be created.

````
mysql> create table table_5_utf8_2 (
    -> `pk` int primary key
    -> ) character set utf8
    -> partition by hash(pk)
    -> partitions 2;
Query OK, 0 rows affected (0.08 sec)
````

**Screenshots**
````
mysql> create table table_5_utf8_2 (
    -> `pk` int primary key
    -> ) character set utf8
    -> partition by hash(pk)
    -> partitions 2;
ERROR 1149 (42000): syntax error! errno: 1 errmsg: syntax error, unexpected HASH, expecting RANGE, in [4:14-17] key:hash
````

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Additional context**
[Hash partition](https://dev.mysql.com/doc/refman/8.0/en/partitioning-types.html) is documented for MySQL.

**Comment by lgqss** [comment]
ENGINE=Rocksdb DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=50 COMMENT='{"resource_tag":"", "replica_num":3, "column" : "pk", "partition_type" : "hash", "partition" : 2}';
这块考虑不周，下一版将会兼容mysql语法
