### ISSUE TITLE
Cannot drop empty database

### ISSUE THREAD

**Issue by zhangysh1995** [baidu/BaikalDB#123]
**Describe the bug**
ERROR 10001 (HY000): database has table

**To Reproduce**

````
show tables;
drop database if exists TestDB;
````

**Expected behavior**
It should drop the given database.

**Screenshots**
````
mysql> show tables;
Empty set (0.00 sec)

mysql> drop database if exists TestDB;
ERROR 10001 (HY000): database has table
````

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Additional context**
N/A

**Comment by lgqss** [comment]
已支持
