### ISSUE TITLE
同一机器上不同raft group的信息为什么要放到一个rocksdb里面？

### ISSUE THREAD

**Issue by LittleTigered** [baidu/BaikalDB#126]
1. 为什么同一台机器上不同raft group的 raft log要存储到一个raft rocksdb里面， 放到不同的rocksdb里面有什么问题吗， 是出于什么考虑？ 
2. 一般来说，raft group都是用uint64的唯一id来标识，如果想使用string(比如集群名，业务层保证唯一)作为唯一id， 会有什么坑么(并不针对baikaldb，只是说对于一个新的kv store这样设计)

**Comment by lgqss** [comment]
1. 可以放到不同的rocksdb实例中，没什么问题
2.不了解这个uint64的id是啥，raft内部的标记是个string，我们给raft的名字是叫region_xxx，保证唯一就行

**Comment by LittleTigered** [comment]
谢谢！
