### ISSUE TITLE
multi-raft连接复用

### ISSUE THREAD

**Issue by LittleTigered** [baidu/BaikalDB#129]
多个raft group， 如果每个raft副本之间都两两链接，那么链接数爆炸。 理论上一个节点上的所有raft group需要复用链接， 这部分优化是在braft中还是BaikalDB， 有相关的code链接发下么， 多谢

**Comment by LittleTigered** [comment]
另外，有没有meta server raft log 和 snapshot的数据格式介绍， 谢谢

**Comment by lgqss** [comment]
> 多个raft group， 如果每个raft副本之间都两两链接，那么链接数爆炸。 理论上一个节点上的所有raft group需要复用链接， 这部分优化是在braft中还是BaikalDB， 有相关的code链接发下么， 多谢

这块raft没做优化，不过brpc默认是单链接模式，就是两台实例的只建立一个连接

**Comment by lgqss** [comment]
> 另外，有没有meta server raft log 和 snapshot的数据格式介绍， 谢谢

raft log和store是一样的，目前meta里有3个group，起了dummpy region id {0，1，2}，raft log保存在了rocksdb里
snapshot就是rocksdb内部的数据直接write成了sst
