### ISSUE TITLE
请问生产环境有多少个region呢？

### ISSUE THREAD

**Issue by Yriuns** [baidu/BaikalDB#133]
我们也使用braft开发database，在测试时遇到一些问题想请教一下：

当region比较多的时候（5节点，5k-10k region），3副本的话平均每个节点3k-6k个region，其中1k-2k是leader
1. 如果网络抖动，大量do_leader_stop后，容易出现pre_vote雪崩的情况
2. 另一个心跳也比较多，如果选举超时时间是1s的话，那就是1s发2次心跳，整个节点来看QPS上万了，开销也不小

想问问是否遇到过类似的问题，以及如何解决呢？谢谢！

**Comment by luobuda** [comment]
我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解

**Comment by Yriuns** [comment]
> 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。

感谢，我们也设置的10s : )
还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？

**Comment by luobuda** [comment]
> > 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。
> 
> 感谢，我们也设置的10s : )
> 还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？
你是说baikaldb的实现吗

**Comment by luobuda** [comment]
> > 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。
> 
> 感谢，我们也设置的10s : )
> 还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？

你说的baikaldb的事务实现吗

**Comment by Yriuns** [comment]
> > > 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。
> > 
> > 
> > 感谢，我们也设置的10s : )
> > 还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？
> 
> 你说的baikaldb的事务实现吗

是的

**Comment by luobuda** [comment]
> > > > 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。
> > > 
> > > 
> > > 感谢，我们也设置的10s : )
> > > 还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？
> > 
> > 
> > 你说的baikaldb的事务实现吗
> 
> 是的

baikaldb的事务目前问题还很多，可以一起交流一下

**Comment by Yriuns** [comment]
> > > > > 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。
> > > > 
> > > > 
> > > > 感谢，我们也设置的10s : )
> > > > 还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？
> > > 
> > > 
> > > 你说的baikaldb的事务实现吗
> > 
> > 
> > 是的
> 
> baikaldb的事务目前问题还很多，可以一起交流一下，的确是有可能读到旧数据的，目前事务隔离级别也没有保证

了解了，我们是利用leader lease来做的

**Comment by luobuda** [comment]
> ，的确是有可能读到旧数



> > > > > > 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。
> > > > > 
> > > > > 
> > > > > 感谢，我们也设置的10s : )
> > > > > 还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？
> > > > 
> > > > 
> > > > 你说的baikaldb的事务实现吗
> > > 
> > > 
> > > 是的
> > 
> > 
> > baikaldb的事务目前问题还很多，可以一起交流一下，的确是有可能读到旧数据的，目前事务隔离级别也没有保证
> 
> 了解了，我们是利用leader lease来做的

是得利用leader lease这种机制，还有raft的false negative问题，不知道你们如何处理的

**Comment by Yriuns** [comment]
> > ，的确是有可能读到旧数
> 
> > > > > > > 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。
> > > > > > 
> > > > > > 
> > > > > > 感谢，我们也设置的10s : )
> > > > > > 还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？
> > > > > 
> > > > > 
> > > > > 你说的baikaldb的事务实现吗
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > baikaldb的事务目前问题还很多，可以一起交流一下，的确是有可能读到旧数据的，目前事务隔离级别也没有保证
> > 
> > 
> > 了解了，我们是利用leader lease来做的
> 
> 是得利用leader lease这种机制，还有raft的false negative问题，不知道你们如何处理的

和你们之前的处理一样，没进2PC的事务都清理掉

**Comment by luobuda** [comment]
> > > ，的确是有可能读到旧数
> > 
> > 
> > > > > > > > 我们服务单节点有1w+region的，设置了较大的选举超时时间(10s)来缓解，欢迎交流学习。
> > > > > > > 
> > > > > > > 
> > > > > > > 感谢，我们也设置的10s : )
> > > > > > > 还有一个问题是：如果旧leader的on_leader_stop还在execution_queue中排队未调用，此时如果来了一个读请求（开启了事务），貌似不会被拒绝，所以有可能读到过期的数据？
> > > > > > 
> > > > > > 
> > > > > > 你说的baikaldb的事务实现吗
> > > > > 
> > > > > 
> > > > > 是的
> > > > 
> > > > 
> > > > baikaldb的事务目前问题还很多，可以一起交流一下，的确是有可能读到旧数据的，目前事务隔离级别也没有保证
> > > 
> > > 
> > > 了解了，我们是利用leader lease来做的
> > 
> > 
> > 是得利用leader lease这种机制，还有raft的false negative问题，不知道你们如何处理的
> 
> 和你们之前的处理一样，没进2PC的事务都清理掉

主要是想问一下这个问题 #https://github.com/baidu/braft/issues/197，能加个即时通讯聊吗
