### ISSUE TITLE
Rocksdb的bazel build文件ROCKSDB_MALLOC_USABLE_SIZE重复定义了

### ISSUE THREAD

**Issue by HuangZhenLiang** [baidu/BaikalDB#135]
如题。另外，咨询一下，rocksdb没有起用jemalloc的原因是什么。

**Comment by luobuda** [comment]
我们单实例可能服务几百G数据，用jemalloc内存占用较大

**Comment by lgqss** [comment]
brpc结合tcmalloc可以看火焰图，jemalloc试用过，在baikaldb上没有看出和tcmalloc有明显差别
