### ISSUE TITLE
通过hint braft库来实现重启不load raft日志

### ISSUE THREAD

**Issue by lyng-x** [baidu/BaikalDB#155]
**问题描述：**
在[这里](https://github.com/baidu/braft/issues/46#issuecomment-414570022)有提到baikaldb实现了一种加速重启的方案，同时
[这里](https://github.com/baidu/BaikalDB/issues/105#issuecomment-685679861)提到<applied_index 就不apply _状态机，也就是所谓的null操作。
但是当有大量写操作时，重启后仍有大量未snapshot的log回放，这导致了大量的io操作实际上影响了混合部署的其他进程，我粗看了baikdb似乎有实现put data与applied_index一起持久化的动作（或者我们应该这么做?），这样就实现了@ipconfigme[提到](https://github.com/baidu/braft/issues/46#issuecomment-403714411)的hint raft库跳过log 避免大量io的操作。
**一种可能的方案：**
重写一下SnapshotReader::load_meta (或为其提供专门的FileAdaptor,并重写read), 针对重启不回放的场景，通过MetaWriter::read_applied_index获取base数据里实际写入的applied_index进行比较替换以指导raft跳过已应用日志?

**Comment by lgqss** [comment]
实现了put data与applied_index一起持久化的动作。
我们目前没有研究过这块内容，按理说应该是可以改写的。
不过这个ssd上的io操作开销应该还好，貌似没有发现被这个影响的情况。

**Comment by lyng-x** [comment]
继续阅读了下代码, region的实现上，on_snapshot_save似乎只填充了snapshot file name到__raft_snapshot_meta里，并没有实际dump出db的数据？ 貌似是通过store的backup接口来实现触发实际备份？如果是这样，则实际的snapshot流程实际就是同步了applied_index到raft层(看gflag默认设置是600s同步一次)。但是快照恢复的流程则需要提前通过store的接口完成生成和同步？

**Comment by lgqss** [comment]
实时snapshot的逻辑在raft/rocksdb_file_system_adaptor.cpp
会把对应的appliedindex也一起发出去，按需发送

**Comment by lyng-x** [comment]
> 实时snapshot的逻辑在raft/rocksdb_file_system_adaptor.cpp
> 会把对应的appliedindex也一起发出去，按需发送

看到了~ install snapshot变得有些巧妙了,避开了全库snapshot.实时快照成本得到了控制。可以由较小的一个snapshot间隔？多问一句，目前snapshot的一个周期实践有没有推荐值？

**Comment by lgqss** [comment]
周期不重要，可以设置1800s，只是用来清理log_entry，我们是做了些判断：https://github.com/baidu/BaikalDB/blob/master/src/store/region.cpp#L3196

**Comment by lyng-x** [comment]
ok, 这块基本了解，期望后续有相关产品文档对架构设计细节有更多描述。thx，issue就先关闭了。
