### ISSUE TITLE
有没有MySQL与BaikalDb相互迁移数据的工具呢

### ISSUE THREAD

**Issue by xiaoqing-yuanfang** [baidu/BaikalDB#16]

**Comment by lgqss** [comment]
我们组是有数据流团队做MySQL到BaikalDB实时同步的工具，只是依赖了内部的一些组件还无法开源。。

**Comment by tullyliu** [comment]
mysql到baikaldb，由于baikaldb是mysql协议的，目前开源的可以选择阿里的otter，我们内部的数据同步系统还在开源改造中，需要一定工作周期。baikaldb到mysql，基准环节就是select导出，增量环节的导出，可能就是直接导出到MQ（考虑kafka）里，还在规划中，如果有兴趣欢迎参与进来~
