### ISSUE TITLE
英文版 wiki 中，中文版链接有误。

### ISSUE THREAD

**Issue by hisenyuan** [baidu/BaikalDB#162]
目前是：https://github.com/baidu/BaikalDB/wiki
看右边目录
应该是：https://github.com/baidu/BaikalDB/wiki/Home-CN

![image](https://user-images.githubusercontent.com/16789019/132672174-5cf6edde-942d-4aa8-bc67-50c221679f4c.png)

**Comment by lgqss** [comment]
已修改，感谢指出
