### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by b0123456789** [baidu/BaikalDB#183]
![111](https://user-images.githubusercontent.com/21169660/180352168-bf98f53e-2fde-4485-8cc1-56402305616e.png)

gcc 版本 12.1.1 20220507 (Red Hat 12.1.1-1) (GCC) 
GNU Make 4.3
fedora 35

**Comment by lgqss** [comment]
看着这个报错在rocksdb里，不知道是不是编译器太新了，如果可以加 -Wno-range-loop-construct试试
