### ISSUE TITLE
请问 BaiKalDB 是百度 Palo 的开源版本吗？ 本项目可用在生产环境吗？ 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [baidu/BaikalDB#19]
请问 BaiKalDB 是百度 Palo 的开源版本吗？ 本项目可用在生产环境吗？

**Comment by baoxuezhao** [comment]
BaikalDB是一个独立的开源项目，不是Palo的开源版本。BaikalDB目前已经应用在百度内部生产环境中，部署了300+的实例。如果你们部署和使用过程中有任何问题，可及时与我们联系。

**Comment by lgqss** [comment]
https://github.com/apache/incubator-doris
百度开源的palo是这个，欢迎使用
