### ISSUE TITLE
编译报错和 protobuf 有关吗？

### ISSUE THREAD

**Issue by HappenLee** [baidu/BaikalDB#20]
ERROR: /home/happen/mycode/BaikalDB/BUILD:506:1: Linking of rule '//:baikalMeta' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -o bazel-out/k8-fastbuild/bin/baikalMeta -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -pass-exit-codes -Wl,-S ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::Options::Options()'

**Comment by baoxuezhao** [comment]
看起来像是zlib的依赖存在问题，你的操作系统版本是什么？

**Comment by HappenLee** [comment]
> 看起来像是zlib的依赖存在问题，你的操作系统版本是什么？

Mint 18.3 我 check 了一下，安装了 zlib1g-dev，是版本有问题吗

**Comment by rttliming** [comment]
ubuntu 16.04编译也碰到了这个问题，zlib1g-dev也安装了

**Comment by yvxiang** [comment]
确实有这个问题，即使是ubuntu 16.04

**Comment by baoxuezhao** [comment]
用的bazel版本是什么

**Comment by yvxiang** [comment]
联系你bazel版本后解决，按文档中的版本来是可以的，不要用最新版本
