### ISSUE TITLE
当前项目的稳定行情况

### ISSUE THREAD

**Issue by yongs207** [baidu/BaikalDB#22]
项目开源已经有一段时间了，是不是节点扩容的功能，是在内部使用的基础，这个开源版本能在生产中使用吗？还有就是性能相当tidb有优势没？

**Comment by lgqss** [comment]
扩容，迁移，负载均衡功能都已具备，内部是在线上使用的。由于运维监控工具的缺乏，目前还不建议外部用户用在重要的生产环境。
做了sysbench，写性能与tidb相当，读性能比tidb差，大约是tidb的70%左右。当然也一直在优化。

**Comment by yongs207** [comment]
写性能由于braft相对tikv的优势，不是理论上有优势才对？tikv都是单线程处理的

**Comment by tigerzhang** [comment]
读性能比 tidb 差主要是什么原因

**Comment by lgqss** [comment]
影响性能的因素还是很多的，rocksdb的基于skiplist的memtable写入性能并不好，写入很多时候瓶颈在此。读取性能的一个只要原因是我们基于pb的存储格式解析耗时比较大，另外一些不必要的内存分配啥的也会影响性能。
@yongs207 tikv单线程处理是指写rocksdb那块单线程吗，抱歉我们并没有仔细研究过tikv内部实现。

**Comment by tullyliu** [comment]
sysbench的测试是直接跟tidb官方测试数据对比的结果，但是tidb使用的服务器硬件跟我们内部线上服务器是有差异的，我们还没有在同样的硬件上运行tidb的sysbench测试集。同时基础测试并不能代表业务场景的性能，如果关注性能，请根据实际的业务sql进行性能测试，这样会有助于选型的决策。

**Comment by yongs207** [comment]
tikv 最新的版本才支持多线程的raft实现
