### ISSUE TITLE
安装部署

### ISSUE THREAD

**Issue by guohengh** [baidu/BaikalDB#229]
安装部署服务没报错，但是端口号没起来，客户端连接不上，还有更详细的安装部署步骤吗？可以加到官方人员沟通吗

**Comment by lgqss** [comment]
首页可以添加微信群
https://github.com/baidu/BaikalDB/wiki/Installation-EN

**Comment by guohengh** [comment]
加了没同意，部署起来了，不会使用，可以推我进群吗，官方大人

**Comment by guohengh** [comment]
加了官方没同意，可以拉我进群吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/BaikalDB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/BaikalDB] 安装部署 (Issue #229)





 
首页可以添加微信群
 https://github.com/baidu/BaikalDB/wiki/Installation-EN

**Comment by lgqss** [comment]
![221695624756_ pic](https://github.com/baidu/BaikalDB/assets/40157860/5e0954ec-b0eb-4072-90be-ea86d4febbe4)
可以加这个群，或者你可以加我wx：lgq0925
