### ISSUE TITLE
rocksdb 数据量特别大的时候，还是全量备份吗？

### ISSUE THREAD

**Issue by xuxiping** [baidu/BaikalDB#23]
如题，当数据量特别大时，全量备份会导致本分时间特别长，是否考虑做增量备份？

**Comment by lgqss** [comment]
全量备份是指raft的snapshot功能吗？
目前开源版本是基于全量写入sst的，内部已经改成了不基于sst了，不会再保存一份额外的数据了，这部分代码正在合入到开源版本，这两天应该会push。

**Comment by xuxiping** [comment]
你们怎么处理 raft快照和rocksdb数据的， 如果不额外保存一份数据， 那raft在使用快照同步其他节点时是直接使用的享有rocksdb文件还是？

**Comment by xuxiping** [comment]
看懂了，braft没对 snapshot_file_system_adaptor做说明。
