### ISSUE TITLE
有没有考虑将原生的KV分离出来，使其可以独立运行

### ISSUE THREAD

**Issue by yongs207** [baidu/BaikalDB#28]
类似tidb于tikv的关系，使得底层的分布式kv由明显的分界，这样可以在kv的基础上开发非sql的基础应用

**Comment by tullyliu** [comment]
目前基于rocksdb或者其他单机引擎的分布式kv实现已经有很多种了，我们再做一遍其实意义不大，我们还是会focus在我们结合数据+索引+查询计划优化的数据库形态上，数据库的应用场景更通用也更贴合我们自己的业务场景
