### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by xuxiping** [baidu/BaikalDB#32]
![baikal](https://user-images.githubusercontent.com/38487648/51818048-51c3ae80-2308-11e9-8100-2391e62073a0.png)
![baikal2](https://user-images.githubusercontent.com/38487648/51818050-525c4500-2308-11e9-932a-b7069bca78e8.png)

**Comment by lgqss** [comment]
不好意思，有份内部代码不小心合入了，我待会提交一版解决这个问题
glog那块报错是否缺少了log目录

**Comment by xuxiping** [comment]
glog 的不要紧

**Comment by lgqss** [comment]
已提交，可以运行了
