### ISSUE TITLE
不使用百度内部日志模块，这个地方是否可以直接 return 0;

### ISSUE THREAD

**Issue by xuxiping** [baidu/BaikalDB#35]
https://github.com/baidu/BaikalDB/blob/90a7ef6f8484271c52ad8d595a181116c8f11884/include/common/log.h#L174

**Comment by lgqss** [comment]
开源版本用的是glog，为了减少配置成本所以写死了一些常用配置，你是想自己配置gflags参数还是怎样？

**Comment by xuxiping** [comment]
开源的版本是不是不应该有写死的常用配置?

**Comment by lgqss** [comment]
这样，为了兼容现状，我再加个gflags：glog_use_default控制是否用写死参数，需要自己配置的可以改成false后自定义配置
不过::google::SetLogDestination还得默认配置
其实一般这么配置glog就够用了，更改目录可以用软链，配置太多容易晕
