### ISSUE TITLE
绑定本机指定ip，而braft时使用的时IP_ANY， 这里一直无法选举leader

### ISSUE THREAD

**Issue by ghost** [baidu/BaikalDB#36]
![2019-01-29 11-26-28](https://user-images.githubusercontent.com/38487648/51882114-c6eebc80-23b8-11e9-98f8-3ebe0975134e.png)

**Comment by lilithliu1** [comment]
是不是之前配置错了启动过一次？把这个环境清空，用当前正确的配置重新启动一次。清空rocksdb目录。

**Comment by xuxiping** [comment]
![1](https://user-images.githubusercontent.com/38487648/51889086-70db4280-23d3-11e9-91d8-3319a53f0ad2.png)
![2](https://user-images.githubusercontent.com/38487648/51889101-7afd4100-23d3-11e9-99f5-570bb4605753.png)

**是第一次运行**

**Comment by lilithliu1** [comment]
我们这个raft的ip是通过hostname2ip方法获得，你把这个peers得配置改成127.0.1.1:8010即可。另外你可以在你的机器上hostname -i 看一下
