### ISSUE TITLE
又又又崩溃了？

### ISSUE THREAD

**Issue by xuxiping** [baidu/BaikalDB#39]
![222](https://user-images.githubusercontent.com/38487648/52684358-f4bf2e00-2f80-11e9-8511-108081ae5f40.png)

**Comment by xuxiping** [comment]
按照readme 一步步来， 还没走到下面这步就这样了。
run script to create baikaldb instance meta-table: sh create_internal_table.sh meta_leader_ip:port

**Comment by lilithliu1** [comment]
你看一下readme流程，是先执行这一步run script to create baikaldb instance meta-table: sh create_internal_table.sh meta_leader_ip:port。再启动baikaldb
