### ISSUE TITLE
脚本内容不统一

### ISSUE THREAD

**Issue by xuxiping** [baidu/BaikalDB#40]
https://github.com/baidu/BaikalDB/blob/e6075dad456926066f09e3fab66b3a8b29bb675f/src/tools/script/create_namespace.sh#L10

https://github.com/baidu/BaikalDB/blob/e6075dad456926066f09e3fab66b3a8b29bb675f/src/tools/script/create_database.sh#L12

**Comment by lilithliu1** [comment]
sorry， 我们将内部的脚本同步出去了。修改一下重新上传
