### ISSUE TITLE
在实际中单节点支持的region数目能够达到多大

### ISSUE THREAD

**Issue by yongs207** [baidu/BaikalDB#41]
1.在百度内部的生成环境中，但节点上拥有的region个数为多少？即一个节点能够支持多少raft group
2.由于braft针对raft group 各个资源基本上是完全独立了，过多的raft group是否会造成资源消耗过多，如多多的心跳

**Comment by lilithliu1** [comment]
我们自己内部在ssd盘上最多的region数量目前在12000， 在disk盘是6000多。过多的raft group会造成资源消耗，但心跳开销很小，目前线上无影响
