### ISSUE TITLE
一个机器多个SSD即启动多个实例，如果配置策略使得同一个raft group 不在相同节点上

### ISSUE THREAD

**Issue by yongs207** [baidu/BaikalDB#43]
分析代码发现 whether_legal_for_select_instance 只是按照一下规则进行选择resource_tag相同, 不在exclude_stores之内, logical_room相同，而在一种一般的场景下如：
一个机器有多块SSD，而针对每一个SSD会启动一个store的实例，当进行region分配时，我们需要针对一个raft group 需要在不同的机器上才能保证数据的安全，为了实现这样的目标我们需要怎样实现配置？

**Comment by lgqss** [comment]
单机多实例部署的话，可以修改为根据ip判断，欢迎提交pr
