### ISSUE TITLE
region 分裂时，开始只有一个节点在对用的raft group中，是否有数据丢失的风险

### ISSUE THREAD

**Issue by yongs207** [baidu/BaikalDB#44]
通过分析代码，发现在region split 是会先创建一个新的region，这是在这个region中只有一个peer，在非tail的分类时，一般就是原来region的leader节点，这时会写本地rocksdb，并且通过短暂阻塞读写实现新的region和老的region的数据保持一致，这是就会更新table 的版本，这样在后续的数据读写时就会使用新的视图（新的region info），这样新的region就可以接收数据读写了，但当新的region可以接收数据读写时，并没有保证当前的raft group 已经有足够多的peer，如果这时出现节点异常，就可能会导致数据丢失。
       从代码分析看region的peer增加是通过心跳处理，在RegionManager::check_peer_count 中判断副本数据不足时才选择添加新的实例到raft group的，而这个过程与region split是互相独立的，并没有发现怎样保证在一个raft group有足够多的peer时，才开始接收新的数据的协同

**Comment by lgqss** [comment]
如果分裂完毕，addpeer之前机器挂了，是有丢数据风险，这块后续是可以作为一个优化点
