### ISSUE TITLE
这个地方怎么有个sleep？

### ISSUE THREAD

**Issue by xuxiping** [baidu/BaikalDB#46]
https://github.com/baidu/BaikalDB/blob/b89421990d8ad32dcaa8f1cf185ed7f80342a148/src/store/store.cpp#L346

**Comment by lgqss** [comment]
这个是因为brpc单个连接一次最多用3个线程调度，如果单个请求涉及到单store很多region的时候，调度会排队。用这个sleep可以并行调度了。。
