### ISSUE TITLE
想问下有谁通过Installation文档正确运行的没？

### ISSUE THREAD

**Issue by x-x-p** [baidu/BaikalDB#50]
https://github.com/baidu/BaikalDB/wiki/Installation-EN

**Comment by lgqss** [comment]
有的，内部还有同学自己用docker搭建自测环境的

**Comment by x-x-p** [comment]
我问的是那些 关注这个repo的  非百度人员， 请不要急着关闭issue。

**Comment by lgqss** [comment]
抱歉，最近比较忙，您是遇到什么问题了吗，我可以看下
