### ISSUE TITLE
已成功删除的数据库还能被查到

### ISSUE THREAD

**Issue by James-Duan** [baidu/BaikalDB#55]
### 描述
    已经删除成功的数据库，在mysql客户端上仍然显示在show databases的结果集中
### 重现步骤
    1. 删除数据库，并确认删除成功
    2. 执行“show databases”，查看结果集
    
![351571124308_ pic](https://user-images.githubusercontent.com/36757235/66886089-d8402d80-f008-11e9-9ba0-f694276fc588.jpg)

### 建议
    为避免引起删除数据库异常歧义，建议show命令仅展示当前状态正常的数据库

**Comment by lgqss** [comment]
内部版本已修复，下周合入github
