### ISSUE TITLE
why use rocksdb 2pc rather than transacton DB

### ISSUE THREAD

**Issue by mqnails** [baidu/BaikalDB#67]
why we use rocksdb 2pc rather than rocksdb transaction db as the local transaction for gloabal transaction?

**Comment by luobuda** [comment]
one distributed transaction may use many regions，so need 2pc to ensure consistency.

**Comment by mqnails** [comment]
thanks for your reply, I know a distributed transacton may involed many regions that not in one node, but those regions in a branch(local) transaction must be in one node, if  those regions stored in one rocksdb instance, we can use rocksdb transaction DB for our purpose.   could you give a detail explain?

**Comment by mqnails** [comment]
In my opinion, we use spanner like mode as distribute 2pc transaction, and we use rocksdb transaction as branch(local) transaction, is it right?  if so, we just consider branch(local) transaction, if all regions involed in branch(local) transaction are store in one rocksdb instance, I think rocksdb transaction DB is enough, due rocksdb 2pc( local 2pc, using two writebatch) has a lower performance.

**Comment by luobuda** [comment]
Sorry I can‘t get your point completely, maybe you can use an example. furthermore, how to deal with ROLLBACK all transaction.

**Comment by mqnails** [comment]
for example,  if we have a distribute 2pc transaction named GTtrans1, GTrans1 involved 2 keys named key1 and key2 seperately on 2 regions named r1 and r2, r1 is on node1 and r2 is on node2.  so we need two branch(local) transaction, one is on node1, the other is one node2.  
  take the branch(local) transcation on node1 for example, it may do following actions
1. judge if key1 is locked or not
2. if key1 is not locked, then lock key1
3. set key1 = newValue
all above steps must be in a transaction, my doubt is why we don't use rocksdb transacton db?  thanks again for your reply.

**Comment by lgqss** [comment]
It's a goodpoint.  rocksdb 2pc is useless in pessimistic_transaction because we don't use its recovery. 
But it's useful if rocksdb support optimistic_transaction Prepare function.

**Comment by mqnails** [comment]
okay, got it , thanks~~
