### ISSUE TITLE
BaikalDB 支持节点扩容和node的分裂不？

### ISSUE THREAD

**Issue by yongs207** [baidu/BaikalDB#8]
如题

**Comment by lilithliu1** [comment]
支持节点扩容。新的store节点在启动之后会上报心跳给meta_server，meta_server识别出新的实例，下次新建region或者如果开启了负载均衡的话，会自动复制数据到新的扩容的节点上。
每个region支持自动分裂，分裂阈值的控制目前是通过创建表时指定的AVG_ROW_LENGTH属性控制的

**Comment by lgqss** [comment]
下个提交会把负载均衡默认开启，使用过程中应该不用处理啥，自动就均衡了

**Comment by yongs207** [comment]
默认负载均衡的版本什么时候提供，或者region分裂会对上层应用的影响有相关的测试没？
