### ISSUE TITLE
SST备份与还原问题

### ISSUE THREAD

**Issue by panghu163** [baidu/BaikalDB#80]
curl -v -o 5_1584106435_60936.sst http://$1/StoreService/backup_region/download/5/data/0
少数据量的时候可以get，没问题，但是大文件的status_code：500的错误.

**Comment by lgqss** [comment]
这块目前需要调整-socket_max_unwritten_bytes=536870912 可支持500M的sst。
后续将会调整接口，因为brpc的http接口不支持持续上传文件，而如果一次性上传将会占用较多内存。
