### ISSUE TITLE
cmake 编译失败

### ISSUE THREAD

**Issue by GOGOYAO** [baidu/BaikalDB#89]
编译环境：
centos 7.7.1908
gcc 8.3.1

```
In file included from /home/work/workspace/BaikalDB/include/common/log.h:22,
                 from /home/work/workspace/BaikalDB/include/common/common.h:48,
                 from /home/work/workspace/BaikalDB/include/engine/rocks_wrapper.h:25,
                 from /home/work/workspace/BaikalDB/include/raft/log_entry_reader.h:17,
                 from /home/work/workspace/BaikalDB/src/raft/log_entry_reader.cpp:15:
/usr/local/include/braft/storage.h: In function 'int braft::gc_dir(const string&)':
/usr/local/include/braft/storage.h:116:9: error: 'COMPACT_GOOGLE_LOG_NOTICE' was not declared in this scope
         LOG(NOTICE) << "Target path not exist, so no need to gc, path: "
         ^~~
/usr/local/include/braft/storage.h:116:9: note: suggested alternative: 'COMPACT_GOOGLE_LOG_FATAL'
In file included from /home/work/workspace/BaikalDB/src/raft/log_entry_reader.cpp:16:
/home/work/workspace/BaikalDB/include/raft/my_raft_log_storage.h: At global scope:
/home/work/workspace/BaikalDB/include/raft/my_raft_log_storage.h:99:9: error: 'int baikaldb::MyRaftLogStorage::append_entries(const std::vector<braft::LogEntry*>&)' marked 'override', but does not override
     int append_entries(const std::vector<braft::LogEntry*>& entries
         ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/baikaldb.dir/build.make:245: CMakeFiles/baikaldb.dir/src/raft/log_entry_reader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/baikaldb.dir/all] Error 2
```

看起来是glog和braft没找到。我已经把这两个库都安装到了/usr/local/include 和 /usr/local/lib。
求问下怎么处理。

另外，CMakeLists.txt第15行， `find_library(RAPIDJSON_LIB NAMES glog)`  是不是应该改为` find_library(RAPIDJSON_LIB NAMES rapidjson)   `

**Comment by lgqss** [comment]
cmake编译暂未维护
目前通过bazel编译和依赖
可以参考travis，centos命令改成yum
install:
    - wget --no-clobber https://github.com/bazelbuild/bazel/releases/download/0.8.1/bazel-0.8.1-installer-linux-x86_64.sh
    - sudo /bin/bash bazel-0.8.1-installer-linux-x86_64.sh
    - sudo apt-get install flex bison libssl-dev
    - sudo apt-get install g++

script:
    - bazel build //:baikaldb
    - bazel build //:baikalStore
    - bazel build //:baikalMeta

**Comment by GOGOYAO** [comment]
> bazel

我参照你们的wiki，试了下bazel。安装过程如下:

![image](https://user-images.githubusercontent.com/18675094/85942114-ded5c180-b959-11ea-87ea-6257d3226198.png)


有以下问题：
```
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/work/workspace/BaikalDB/tools/bazel.rc
Starting local Bazel server and connecting to it...
ERROR: /home/work/workspace/BaikalDB/WORKSPACE:1:1: name 'http_archive' is not defined
ERROR: /home/work/workspace/BaikalDB/WORKSPACE:12:1: name 'http_archive' is not defined
ERROR: /home/work/workspace/BaikalDB/WORKSPACE:23:1: name 'http_archive' is not defined
ERROR: /home/work/workspace/BaikalDB/WORKSPACE:34:1: name 'new_http_archive' is not defined
ERROR: /home/work/workspace/BaikalDB/WORKSPACE:46:1: name 'new_http_archive' is not defined
ERROR: /home/work/workspace/BaikalDB/WORKSPACE:54:1: name 'git_repository' is not defined
ERROR: error loading package '': Encountered error while reading extension file 'boost/boost.bzl': no such package '@com_github_nelhage_rules_boost//boost': error loading package 'external': Could not load //external package
INFO: Elapsed time: 5.272s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by lgqss** [comment]
bazel需要0.8.1版本的，bazel新旧版本语法不能兼容
新bazel也在适配中，不过适配完了新bazel后就不兼容旧bazel了

**Comment by GOGOYAO** [comment]
> sudo /bin/bash bazel-0.8.1-installer-linux-x86_64.sh

更新版本开始下载依赖模块了。不过下载好慢，rocksdb这些我本地都装过了。能直接用本地的么

**Comment by lgqss** [comment]
不行哦，bazel都会搞到本地，不过第一次慢，后续的都是缓存起来的
而且有时候下载会失败，需要多下载几次，boost我遇到过好几次失败

**Comment by GOGOYAO** [comment]
> 而且有时候下载会失败，需要多下载几次，boost我遇到过好几次失败

是的。失败了很多次终于成功了。考虑支持下cmake么？用clion看代码，得有个cmake才行。

**Comment by tullyliu** [comment]
> > 而且有时候下载会失败，需要多下载几次，boost我遇到过好几次失败
> 
> 是的。失败了很多次终于成功了。考虑支持下cmake么？用clion看代码，得有个cmake才行。

近期搞一个

**Comment by GOGOYAO** [comment]
> > > 而且有时候下载会失败，需要多下载几次，boost我遇到过好几次失败
> > 
> > 
> > 是的。失败了很多次终于成功了。考虑支持下cmake么？用clion看代码，得有个cmake才行。
> 
> 近期搞一个

期待

**Comment by tullyliu** [comment]
> > > > 而且有时候下载会失败，需要多下载几次，boost我遇到过好几次失败
> > > 
> > > 
> > > 是的。失败了很多次终于成功了。考虑支持下cmake么？用clion看代码，得有个cmake才行。
> > 
> > 
> > 近期搞一个
> 
> 期待

你们考虑内部应用落地吗？还只是个人兴趣研究？

**Comment by GOGOYAO** [comment]
> > > > > 而且有时候下载会失败，需要多下载几次，boost我遇到过好几次失败
> > > > 
> > > > 
> > > > 是的。失败了很多次终于成功了。考虑支持下cmake么？用clion看代码，得有个cmake才行。
> > > 
> > > 
> > > 近期搞一个
> > 
> > 
> > 期待
> 
> 你们考虑内部应用落地吗？还只是个人兴趣研究？

个人研究

**Comment by tullyliu** [comment]
> > > > > > 而且有时候下载会失败，需要多下载几次，boost我遇到过好几次失败
> > > > > 
> > > > > 
> > > > > 是的。失败了很多次终于成功了。考虑支持下cmake么？用clion看代码，得有个cmake才行。
> > > > 
> > > > 
> > > > 近期搞一个
> > > 
> > > 
> > > 期待
> > 
> > 
> > 你们考虑内部应用落地吗？还只是个人兴趣研究？
> 
> 个人研究

欢迎关注和交流

**Comment by tullyliu** [comment]
> 编译环境：
> centos 7.7.1908
> gcc 8.3.1
> 
> ```
> In file included from /home/work/workspace/BaikalDB/include/common/log.h:22,
>                  from /home/work/workspace/BaikalDB/include/common/common.h:48,
>                  from /home/work/workspace/BaikalDB/include/engine/rocks_wrapper.h:25,
>                  from /home/work/workspace/BaikalDB/include/raft/log_entry_reader.h:17,
>                  from /home/work/workspace/BaikalDB/src/raft/log_entry_reader.cpp:15:
> /usr/local/include/braft/storage.h: In function 'int braft::gc_dir(const string&)':
> /usr/local/include/braft/storage.h:116:9: error: 'COMPACT_GOOGLE_LOG_NOTICE' was not declared in this scope
>          LOG(NOTICE) << "Target path not exist, so no need to gc, path: "
>          ^~~
> /usr/local/include/braft/storage.h:116:9: note: suggested alternative: 'COMPACT_GOOGLE_LOG_FATAL'
> In file included from /home/work/workspace/BaikalDB/src/raft/log_entry_reader.cpp:16:
> /home/work/workspace/BaikalDB/include/raft/my_raft_log_storage.h: At global scope:
> /home/work/workspace/BaikalDB/include/raft/my_raft_log_storage.h:99:9: error: 'int baikaldb::MyRaftLogStorage::append_entries(const std::vector<braft::LogEntry*>&)' marked 'override', but does not override
>      int append_entries(const std::vector<braft::LogEntry*>& entries
>          ^~~~~~~~~~~~~~
> make[2]: *** [CMakeFiles/baikaldb.dir/build.make:245: CMakeFiles/baikaldb.dir/src/raft/log_entry_reader.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/baikaldb.dir/all] Error 2
> ```
> 
> 看起来是glog和braft没找到。我已经把这两个库都安装到了/usr/local/include 和 /usr/local/lib。
> 求问下怎么处理。
> 
> 另外，CMakeLists.txt第15行， `find_library(RAPIDJSON_LIB NAMES glog)` 是不是应该改为`find_library(RAPIDJSON_LIB NAMES rapidjson) `

cmake 修正了，请参考https://github.com/baidu/BaikalDB/wiki/Compile-EN

**Comment by linuxpham** [comment]
> 编译环境：
> centos 7.7.1908
> gcc 8.3.1
> 
> ```
> In file included from /home/work/workspace/BaikalDB/include/common/log.h:22,
>                  from /home/work/workspace/BaikalDB/include/common/common.h:48,
>                  from /home/work/workspace/BaikalDB/include/engine/rocks_wrapper.h:25,
>                  from /home/work/workspace/BaikalDB/include/raft/log_entry_reader.h:17,
>                  from /home/work/workspace/BaikalDB/src/raft/log_entry_reader.cpp:15:
> /usr/local/include/braft/storage.h: In function 'int braft::gc_dir(const string&)':
> /usr/local/include/braft/storage.h:116:9: error: 'COMPACT_GOOGLE_LOG_NOTICE' was not declared in this scope
>          LOG(NOTICE) << "Target path not exist, so no need to gc, path: "
>          ^~~
> /usr/local/include/braft/storage.h:116:9: note: suggested alternative: 'COMPACT_GOOGLE_LOG_FATAL'
> In file included from /home/work/workspace/BaikalDB/src/raft/log_entry_reader.cpp:16:
> /home/work/workspace/BaikalDB/include/raft/my_raft_log_storage.h: At global scope:
> /home/work/workspace/BaikalDB/include/raft/my_raft_log_storage.h:99:9: error: 'int baikaldb::MyRaftLogStorage::append_entries(const std::vector<braft::LogEntry*>&)' marked 'override', but does not override
>      int append_entries(const std::vector<braft::LogEntry*>& entries
>          ^~~~~~~~~~~~~~
> make[2]: *** [CMakeFiles/baikaldb.dir/build.make:245: CMakeFiles/baikaldb.dir/src/raft/log_entry_reader.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/baikaldb.dir/all] Error 2
> ```
> 
> 看起来是glog和braft没找到。我已经把这两个库都安装到了/usr/local/include 和 /usr/local/lib。
> 求问下怎么处理。
> 
> 另外，CMakeLists.txt第15行， `find_library(RAPIDJSON_LIB NAMES glog)` 是不是应该改为`find_library(RAPIDJSON_LIB NAMES rapidjson) `

You can follow these steps (build the third party as static library):
git clone --recurse https://github.com/baidu/BaikalDB.git
cd BaikalDB
mkdir -p _build && cd _build
cmake -DWITH_TESTS=OFF -DWITH_BAIKAL_CLIENT=ON -DWITH_SYSTEM_LIBS=OFF -DCMAKE_BUILD_TYPE:STRING=Release ../
make all -j 4

Detail: #96

**Comment by fankux** [comment]
@linuxpham Hi there, as we discussed compile issue a few days ago, could you please go to your rocksdb source path in your Ubuntu18.04 and run the command: `sh ./build_tools/build_detect_platform output_file`, and paste 'output_file' content to here for me?   #96 
It is your case that will help us improve the robustness of Cmake compiling. : )

**Comment by linuxpham** [comment]
@fankux :

bash ./_build/third-party/rocksdb/src/extern_rocksdb/build_tools/build_detect_platform out_debug/rocksdb_output_file

Anh here is the result:

```
CC=cc
CXX=g++
PLATFORM=OS_LINUX
PLATFORM_LDFLAGS= -lpthread -lrt -lsnappy -lgflags -lz -lbz2 -llz4 -lzstd -lnuma -ltbb
JAVA_LDFLAGS= -lpthread -lrt -lsnappy -lz -lbz2 -llz4 -lzstd -lnuma -ltbb
JAVA_STATIC_LDFLAGS= -lpthread -lrt
VALGRIND_VER=
PLATFORM_CCFLAGS= -DROCKSDB_PLATFORM_POSIX -DROCKSDB_LIB_IO_POSIX  -DOS_LINUX -fno-builtin-memcmp -DROCKSDB_FALLOCATE_PRESENT -DSNAPPY -DGFLAGS=1 -DZLIB -DBZIP2 -DLZ4 -DZSTD -DNUMA -DTBB -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_BACKTRACE -DROCKSDB_RANGESYNC_PRESENT -DROCKSDB_SCHED_GETCPU_PRESENT -march=native   -DHAVE_SSE42  -DHAVE_PCLMUL  -DHAVE_AVX2 -DHAVE_UINT128_EXTENSION -DROCKSDB_SUPPORT_THREAD_LOCAL
PLATFORM_CXXFLAGS=-std=c++11  -faligned-new -DHAVE_ALIGNED_NEW -DROCKSDB_PLATFORM_POSIX -DROCKSDB_LIB_IO_POSIX  -DOS_LINUX -fno-builtin-memcmp -DROCKSDB_FALLOCATE_PRESENT -DSNAPPY -DGFLAGS=1 -DZLIB -DBZIP2 -DLZ4 -DZSTD -DNUMA -DTBB -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_BACKTRACE -DROCKSDB_RANGESYNC_PRESENT -DROCKSDB_SCHED_GETCPU_PRESENT -march=native   -DHAVE_SSE42  -DHAVE_PCLMUL  -DHAVE_AVX2 -DHAVE_UINT128_EXTENSION -DROCKSDB_SUPPORT_THREAD_LOCAL
PLATFORM_SHARED_CFLAGS=-fPIC
PLATFORM_SHARED_EXT=so
PLATFORM_SHARED_LDFLAGS=-Wl,--no-as-needed -shared -Wl,-soname -Wl,
PLATFORM_SHARED_VERSIONED=true
EXEC_LDFLAGS=-ldl
JEMALLOC_INCLUDE=
JEMALLOC_LIB=
ROCKSDB_MAJOR=
ROCKSDB_MINOR=
ROCKSDB_PATCH=
CLANG_SCAN_BUILD=scan-build
CLANG_ANALYZER=/usr/bin/clang++
PROFILING_FLAGS=-pg
FIND=find
WATCH=watch
JEMALLOC=1
WITH_JEMALLOC_FLAG=1
LUA_PATH=
USE_FOLLY_DISTRIBUTED_MUTEX=1
```

**Comment by linuxpham** [comment]
@fankux 

bash ./_build/third-party/leveldb/src/extern_leveldb/build_detect_platform out_debug/leveldb_output_file level

Anh here is the result:

```
SOURCES= port/port_posix.cc
MEMENV_SOURCES=helpers/memenv/memenv.cc
CC=cc
CXX=g++
PLATFORM=OS_LINUX
PLATFORM_LDFLAGS=-pthread
PLATFORM_LIBS= -lsnappy -ltcmalloc
PLATFORM_CCFLAGS= -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY
PLATFORM_CXXFLAGS=-std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY
PLATFORM_SHARED_CFLAGS=-fPIC
PLATFORM_SHARED_EXT=so
PLATFORM_SHARED_LDFLAGS=-shared -Wl,-soname -Wl,
PLATFORM_SHARED_VERSIONED=true
```

**Comment by fankux** [comment]
@linuxpham Thanks, it's helpful!
