### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by carr123** [baidu/BaikalDB#93]
提个小小的建议哦，
1. 可以把编译好的可执行文件放到release下
2. 可以写一些教程，原理讲解啥的
3. 可以多一些案例分享

祝baikaldb 成功！

**Comment by tullyliu** [comment]
关于2和3，请关注我们的oschina 博客，https://my.oschina.net/BaikalDB，欢迎关注，会持续推出文章，同步也会更新到 github wiki 里
关于1，后续会提供 dockfile

**Comment by tullyliu** [comment]
> 提个小小的建议哦，
> 
> 1. 可以把编译好的可执行文件放到release下
> 2. 可以写一些教程，原理讲解啥的
> 3. 可以多一些案例分享
> 
> 祝baikaldb 成功！

如果希望在自己的业务落地使用，可以联系我们深入讨论下。
