### ISSUE TITLE
Build error in Ubuntu 18

### ISSUE THREAD

**Issue by linuxpham** [baidu/BaikalDB#96]
hi Admin,
I compiled BaikalDB from source
git clone --recurse https://github.com/baidu/BaikalDB.git
cd BaikalDB
mkdir -p _build && cd _build
cmake -DWITH_BAIKAL_CLIENT=ON -DWITH_SYSTEM_LIBS=OFF -DCMAKE_BUILD_TYPE:STRING=Release ../
make all -j 4

I see these errors :

/mnt/data/temp/baidu/BaikalDB/_build/third-party/rocksdb/src/extern_rocksdb/./util/compression.h:115: undefined reference to `ZSTD_freeDCtx'
/mnt/data/temp/baidu/BaikalDB/_build/third-party/rocksdb/src/extern_rocksdb/./util/compression.h:367: undefined reference to `ZSTD_freeCCtx'
/mnt/data/temp/baidu/BaikalDB/_build/third-party/rocksdb/src/extern_rocksdb/./util/compression.h:191: undefined reference to `ZSTD_freeCDict'
collect2: error: ld returned 1 exit status
CMakeFiles/baikalMeta.dir/build.make:419: recipe for target 'baikalMeta' failed
make[2]: *** [baikalMeta] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/baikalMeta.dir/all' failed
make[1]: *** [CMakeFiles/baikalMeta.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fankux** [comment]
Looks like lacks of zstd lib, may be there exist some weird option enabled which is unexpected, I'll figure it out.

**Comment by linuxpham** [comment]
I tried to edit CmakeFile.txt and rocksdb.cmake 

Add : find_package(zstd REQUIRED CONFIG)
add : zstd::libzstd_static (or zstd::libzstd_shared) in "DEP_LIB" or "target_link_libraries".

But this error still exist : party/rocksdb/src/extern_rocksdb/./util/compression.h:367: undefined reference to ZSTD_freeCCtx'

**Comment by fankux** [comment]
Have you modified any build scripts or change the version of rocksdb?  
Try to follow these steps:
1. Go to path '/mnt/data/temp/baidu/BaikalDB/_build/third-party/rocksdb/src/extern_rocksdb/' and run default build command:  'PORTABLE=1 make static_lib', to see if this good to go. If not, it's an issue of Rocksdb itself.

2. Install the zstd as rocksdb doc describe: https://github.com/facebook/rocksdb/blob/master/INSTALL.md#supported-platforms. But this is unexpected way because zstd is not needed by default.

**Comment by linuxpham** [comment]
I tried to build this source code:

1. The first : (not modifed any codes)
git clone --recurse https://github.com/baidu/BaikalDB.git
cd BaikalDB
mkdir -p _build && cd _build
cmake -DWITH_TESTS=OFF -DWITH_BAIKAL_CLIENT=ON -DWITH_SYSTEM_LIBS=OFF -DCMAKE_BUILD_TYPE:STRING=Release ../

Everything is compiled in third-party (SUCCESS), but there is some errors when linking step.

There is error: 
```/mnt/data/temp/baidu/BaikalDB/_build/third-party/rocksdb/src/extern_rocksdb/./util/compression.h:115: undefined reference to ZSTD_freeDCtx' /mnt/data/temp/baidu/BaikalDB/_build/third-party/rocksdb/src/extern_rocksdb/./util/compression.h:367: undefined reference to ZSTD_freeCCtx'
/mnt/data/temp/baidu/BaikalDB/_build/third-party/rocksdb/src/extern_rocksdb/./util/compression.h:191: undefined reference to `ZSTD_freeCDict'
collect2: error: ld returned 1 exit status
CMakeFiles/baikalMeta.dir/build.make:419: recipe for target 'baikalMeta' failed
make[2]: *** [baikalMeta] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/baikalMeta.dir/all' failed
make[1]: *** [CMakeFiles/baikalMeta.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2```

2. The second: I tried to edit some lines in the CMake file (CmakeFile.txt and rocksdb.cmake). These errors are still showing.

Do you have me any suggestion?

**Comment by linuxpham** [comment]
This is screen after I run command : cmake -DWITH_TESTS=OFF -DWITH_BAIKAL_CLIENT=ON -DWITH_SYSTEM_LIBS=OFF -DCMAKE_BUILD_TYPE:STRING=Release ../

<img width="1671" alt="Screen Shot 2020-07-13 at 13 33 10" src="https://user-images.githubusercontent.com/154762/87277883-6819f600-c50d-11ea-8193-11045da222cd.png">

**Comment by linuxpham** [comment]
Os system: ubuntu 18

gcc (Ubuntu 9.3.0-11ubuntu0~18.04.1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ (Ubuntu 9.3.0-11ubuntu0~18.04.1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake version 3.16.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by fankux** [comment]
Run `ldconfig -p | grep zstd` to check if there is a zstd in your system, if so, try to modify 'CMakeLists.txt:334' to:

SET(DEP_LIB
        ${DEP_LIB}
        ${ZLIB_LIBRARIES}
        **zstd**
        ${OPENSSL_SSL_LIBRARY}
        ${OPENSSL_CRYPTO_LIBRARY}
        dl
        rt
        ${CMAKE_THREAD_LIBS_INIT}
        )

**Comment by linuxpham** [comment]
It is a  success now. 

<img width="600" alt="Screen Shot 2020-07-13 at 19 42 43" src="https://user-images.githubusercontent.com/154762/87305640-083d4280-c541-11ea-8921-bd2dd9950ecd.png">

Thank you so much!
