### ISSUE TITLE
MySQL Compatibility ?

### ISSUE THREAD

**Issue by linuxpham** [baidu/BaikalDB#97]
Hi admin,

I try to test :

<img width="1663" alt="Screen Shot 2020-07-13 at 21 53 53" src="https://user-images.githubusercontent.com/154762/87319075-59eec880-c553-11ea-9c03-fc1cc9dd1b74.png">

mysql --host=127.0.0.1 --port=5000 -u root -p:
CREATE DATABASE menagerie
show databases; => empty

<img width="1526" alt="Screen Shot 2020-07-13 at 21 52 29" src="https://user-images.githubusercontent.com/154762/87318898-290e9380-c553-11ea-9445-2580f814deb8.png">

How I can use BaiKalDB from my source code? Must I use "baikal-client" library?
Is there any document to guide usage? I can not understand about namespace, database, table ??

**Comment by lgqss** [comment]
You should use add_privilege.sh to add db privilege. I will write this to the wiki https://github.com/baidu/BaikalDB/wiki/User-Guide

**Comment by lgqss** [comment]
database and table is same as mysql
namespace is bind to user. So you can create the same database in diffrent namespaces

**Comment by tullyliu** [comment]
you can use any mysql driver to connect baikaldb server. baikal client is a production-level and high performance mysql client library written by c++.

**Comment by linuxpham** [comment]
> database and table is same as mysql
> namespace is bind to user. So you can create the same database in diffrent namespaces



> you can use any mysql driver to connect baikaldb server. baikal client is a production-level and high performance mysql client library written by c++.

A user can create many namespaces. Every namespace have many databases (can the same database in different namespaces) => I use Mysql client library (ex: Poco MYSQL) to connect to database (zzzzz), with URI : host=127.0.0.1;port=3306;user=yyyy;password=xxxxx;db=zzzzz;compress=true;auto-reconnect=true

How can BaiKalDB detect the namespace of database (zzzzz) ???

**Comment by luobuda** [comment]
> > database and table is same as mysql
> > namespace is bind to user. So you can create the same database in diffrent namespaces
> 
> > you can use any mysql driver to connect baikaldb server. baikal client is a production-level and high performance mysql client library written by c++.
> 
> A user can create many namespaces. Every namespace can have many databases (can the same database in different namespaces) => I use Mysql client library (ex: Poco MYSQL) to connect to database (zzzzz), with URI : host=127.0.0.1;port=3306;user=yyyy;password=xxxxx;db=zzzzz;compress=true;auto-reconnect=true
> 
> How can BaiKalDB detect the namespace of database (zzzzz) ???

Ower username is globally unique，but there is a problem，e.g：root.
Thank you for your question，we will fix it.

**Comment by lgqss** [comment]
> > database and table is same as mysql
> > namespace is bind to user. So you can create the same database in diffrent namespaces
> 
> > you can use any mysql driver to connect baikaldb server. baikal client is a production-level and high performance mysql client library written by c++.
> 
> A user can create many namespaces. Every namespace can have many databases (can the same database in different namespaces) => I use Mysql client library (ex: Poco MYSQL) to connect to database (zzzzz), with URI : host=127.0.0.1;port=3306;user=yyyy;password=xxxxx;db=zzzzz;compress=true;auto-reconnect=true
> 
> How can BaiKalDB detect the namespace of database (zzzzz) ??? Does Baikal detect the namespace by account (username + password) ?

A user can create only one namespace. Many users can bind to one namaspace

**Comment by lgqss** [comment]
> You should use add_privilege.sh to add db privilege. I will write this to the wiki https://github.com/baidu/BaikalDB/wiki/User-Guide

You can see the wiki(I've already update it)：https://github.com/baidu/BaikalDB/wiki/User-Guide#baikaldb%E7%9A%84%E9%80%BB%E8%BE%91%E5%88%92%E5%88%86%E5%92%8C%E7%89%A9%E7%90%86%E5%88%92%E5%88%86
